name: simple_weather_app
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  geolocator: ^9.0.1
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.0.1
  oktoast: ^3.2.0
  lottie: ^1.3.0
  equatable: ^0.6.1
  http: ^0.13.4
  flutter_spinkit: ^5.1.0
  geocode: 1.0.1
  get: ^4.6.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/